<script src="<?= base_url('assets/assets3/') ?>vendor/jquery/jquery-3.2.1.min.js"></script>
<script src="<?= base_url('assets/assets3/') ?>vendor/animsition/js/animsition.min.js"></script>
<script src="<?= base_url('assets/assets3/') ?>vendor/bootstrap/js/popper.js"></script>
<script src="<?= base_url('assets/assets3/') ?>vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="<?= base_url('assets/assets3/') ?>vendor/select2/select2.min.js"></script>
<script src="<?= base_url('assets/assets3/') ?>vendor/daterangepicker/moment.min.js"></script>
<script src="<?= base_url('assets/assets3/') ?>vendor/daterangepicker/daterangepicker.js"></script>
<script src="<?= base_url('assets/assets3/') ?>vendor/countdowntime/countdowntime.js"></script>
<script src="<?= base_url('assets/assets3/') ?>js/main.js"></script>